# Generated by Django 5.2.7 on 2025-12-14 10:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=400, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='IMGnews/for_title/', verbose_name='Фото')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Когда новость станет видна пользователям', verbose_name='Дата добавления')),
                ('is_published', models.BooleanField(default=True, help_text='Отображать новость на сайте', verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='Текс комментария')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='news.comment', verbose_name='Ответ на комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=400, verbose_name='Заголовок блока')),
                ('content', models.TextField(verbose_name='Содержание блока')),
                ('image', models.ImageField(blank=True, null=True, upload_to='IMGnews/blocks', verbose_name='Изображение для блока')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок блоков')),
                ('background_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет фона')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='news.news', verbose_name='Блок новости')),
            ],
            options={
                'verbose_name': 'Блок новости',
                'verbose_name_plural': 'Блоки новостей',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reaction_type', models.IntegerField(choices=[(1, '👍'), (-1, '👎')], default=(1, '👍'), verbose_name='Тип реакции')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='news.comment', verbose_name='Комментарий')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='news.news', verbose_name='Новость')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Реакция',
                'verbose_name_plural': 'Реакции',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'comment'), ('user', 'news')},
            },
        ),
    ]
