# Generated by Django 5.2.7 on 2025-12-16 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_reaction_id_alter_reaction_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsblock',
            name='background_color',
        ),
    ]
